theme: jekyll-theme-minimal
title: -------------------------
subtitle: Gloria Buritica
description: gloria.buritica@sorbonne-universite.fr 
show_downloads: FALSE
logo: /docs/foto.jpg
google_site_verification: "qO0ypQFjMAJu3kmyFYH_uAHSR7KUPr6s4WiyZeX33xQ"
google_analytics: UA
plugins:
  - jekyll-sitemap

