theme: jekyll-theme-minimal
title: ---------------------------
subtitle: Gloria Buriticá
description: gloria.buritica@upmc.fr 
show_downloads: FALSE
logo: /docs/foto.jpg
google_analytics: UA-140077097-1
