theme: jekyll-theme-minimal
title: ---------------------------
subtitle: Gloria Buriticá
description: gloria.buritica@upmc.fr Sorbonne Université - LPSM - Campus Pierre et Marie Curie, 4 place Jussieu, 75005 Paris, Office 15-16 208.
show_downloads: FALSE
logo: /docs/foto.jpg
google_analytics: UA-140077097-1
