theme: jekyll-theme-minimal
title: -----------------------
subtitle: Gloria Buritica
description: gloria.buritica@upmc.fr 
show_downloads: FALSE
logo: /docs/foto.jpg
google_analytics: UA
plugins:
  - jekyll-sitemap


